import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import productsRouter from "./products";
import inventoryRouter from "./inventory";
import suppliersRouter from "./suppliers";
import quotesRouter from "./quotes";
import manufacturingRouter from "./manufacturing";
import hrRouter from "./hr";
import payrollRouter from "./payroll";
import accountingRouter from "./accounting";
import notificationsRouter from "./notifications";
import activityRouter from "./activity";
import dashboardRouter from "./dashboard";
import powerbiRouter from "./powerbi";
import productionRouter from "./production";
import supplierPortalRouter from "./supplier-portal";
import hrPortalRouter from "./hr-portal";
import workerPortalRouter from "./worker-portal";
import salesManagerRouter from "./sales-manager";
import customerPortalRouter from "./customer-portal";
import bulkRouter from "./bulk";
import settingsRouter from "./settings";
import accountsRouter from "./accounts";
import journalEntriesRouter from "./journal-entries";
import financialReportsRouter from "./financial-reports";
import accrualsRouter from "./accruals";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(productsRouter);
router.use(inventoryRouter);
router.use(suppliersRouter);
router.use(quotesRouter);
router.use(manufacturingRouter);
router.use(hrRouter);
router.use(payrollRouter);
router.use(accountingRouter);
router.use(notificationsRouter);
router.use(activityRouter);
router.use(dashboardRouter);
router.use(powerbiRouter);
router.use(productionRouter);
router.use(supplierPortalRouter);
router.use(hrPortalRouter);
router.use(workerPortalRouter);
router.use(salesManagerRouter);
router.use(customerPortalRouter);
router.use(bulkRouter);
router.use(settingsRouter);
router.use(accountsRouter);
router.use(journalEntriesRouter);
router.use(financialReportsRouter);
router.use(accrualsRouter);

export default router;
