import { Router } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import productsRouter from "./products";
import inventoryRouter from "./inventory";
import analyticsDeckRouter from "./analytics-deck";
import suppliersRouter from "./suppliers";
import quotesRouter from "./quotes";
import cogmRouter from "./cogm";
import priceProposalsRouter from "./price-proposals";
import manufacturingRouter from "./manufacturing";
import hrRouter from "./hr";
import payrollRouter from "./payroll";
import accountingRouter from "./accounting";
import notificationsRouter from "./notifications";
import activityRouter from "./activity";
import dashboardRouter from "./dashboard";
import powerbiRouter from "./powerbi";
import productionRouter from "./production";
import supplierPortalRouter from "./supplier-portal";
import hrPortalRouter from "./hr-portal";
import workerPortalRouter from "./worker-portal";
import salesManagerRouter from "./sales-manager";
import customerPortalRouter from "./customer-portal";
import bulkRouter from "./bulk";
import settingsRouter from "./settings";
import accountsRouter from "./accounts";
import journalEntriesRouter from "./journal-entries";
import financialReportsRouter from "./financial-reports";
import accrualsRouter from "./accruals";
import imagesRouter from "./images";
import dashboardThemesRouter from "./dashboard-themes";
import currencyRouter from "./currency";
import customerProfileRouter from "./customer-profile";
const router = Router();
router.use(healthRouter);
router.use(dashboardThemesRouter);
router.use(authRouter);
router.use(currencyRouter);
router.use(customerProfileRouter);
router.use(usersRouter);
router.use(productsRouter);
router.use(inventoryRouter);
router.use(analyticsDeckRouter);
router.use(suppliersRouter);
router.use(quotesRouter);
router.use(cogmRouter);
router.use(priceProposalsRouter);
router.use(manufacturingRouter);
router.use(hrRouter);
router.use(payrollRouter);
router.use(accountingRouter);
router.use(notificationsRouter);
router.use(activityRouter);
router.use(dashboardRouter);
router.use(powerbiRouter);
router.use(productionRouter);
router.use(supplierPortalRouter);
router.use(hrPortalRouter);
router.use(workerPortalRouter);
router.use(salesManagerRouter);
router.use(customerPortalRouter);
router.use(bulkRouter);
router.use(settingsRouter);
router.use(accountsRouter);
router.use(journalEntriesRouter);
router.use(financialReportsRouter);
router.use(accrualsRouter);
router.use(imagesRouter);
export default router;
